### ISSUE TITLE
Fails to start after upgrade

### ISSUE THREAD

**Issue by ndarilek** [rancher/k3s#1053]
Recently upgraded from 0.5 to 0.10.2, and now `k3s server` won't start. Here is a full log of my startup attempt. This is a single-node hobby setup with the same node as server and worker:

```
time="2019-11-12T22:33:25.332317785+01:00" level=info msg="Starting k3s v0.10.2 (8833bfd9)"
time="2019-11-12T22:33:25.338757690+01:00" level=info msg="Kine listening on unix://kine.sock"
time="2019-11-12T22:33:25.340420791+01:00" level=info msg="Fetching bootstrap data from etcd"
time="2019-11-12T22:33:25.372427924+01:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=unknown --authorization-mode=Node,RBAC --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix://kine.sock --insecure-port=0 --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=k3s --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key"
Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production environments.
I1112 22:33:25.375278   26468 server.go:650] external host was not specified, using XXX.XXX.XXX.XXX
I1112 22:33:25.375715   26468 server.go:162] Version: v1.16.2-k3s.1
I1112 22:33:25.386070   26468 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1112 22:33:25.386103   26468 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I1112 22:33:25.387468   26468 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1112 22:33:25.387495   26468 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
I1112 22:33:25.426995   26468 master.go:259] Using reconciler: lease
I1112 22:33:25.526183   26468 rest.go:115] the default service ipfamily for this cluster is: IPv4
W1112 22:33:26.034658   26468 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
W1112 22:33:26.055078   26468 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
W1112 22:33:26.075262   26468 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W1112 22:33:26.078878   26468 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
W1112 22:33:26.091025   26468 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W1112 22:33:26.111184   26468 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
W1112 22:33:26.111213   26468 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
I1112 22:33:26.121732   26468 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1112 22:33:26.121761   26468 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.
time="2019-11-12T22:33:26.134430066+01:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --port=10251 --secure-port=0"
time="2019-11-12T22:33:26.135420721+01:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
I1112 22:33:26.155725   26468 server.go:143] Version: v1.16.2-k3s.1
I1112 22:33:26.155897   26468 controllermanager.go:161] Version: v1.16.2-k3s.1
I1112 22:33:26.155979   26468 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
I1112 22:33:26.157422   26468 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
W1112 22:33:26.158490   26468 authorization.go:47] Authorization is disabled
W1112 22:33:26.158514   26468 authentication.go:79] Authentication is disabled
I1112 22:33:26.158531   26468 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1112 22:33:28.865365   26468 secure_serving.go:123] Serving securely on 127.0.0.1:6444
I1112 22:33:28.865452   26468 autoregister_controller.go:140] Starting autoregister controller
I1112 22:33:28.865462   26468 cache.go:32] Waiting for caches to sync for autoregister controller
I1112 22:33:28.865465   26468 available_controller.go:383] Starting AvailableConditionController
I1112 22:33:28.865514   26468 cache.go:32] Waiting for caches to sync for AvailableConditionController controller
I1112 22:33:28.865632   26468 apiservice_controller.go:94] Starting APIServiceRegistrationController
I1112 22:33:28.865637   26468 crdregistration_controller.go:111] Starting crd-autoregister controller
I1112 22:33:28.865669   26468 controller.go:85] Starting OpenAPI controller
I1112 22:33:28.865705   26468 customresource_discovery_controller.go:208] Starting DiscoveryController
I1112 22:33:28.865732   26468 naming_controller.go:288] Starting NamingConditionController
I1112 22:33:28.865755   26468 establishing_controller.go:73] Starting EstablishingController
I1112 22:33:28.865780   26468 nonstructuralschema_controller.go:191] Starting NonStructuralSchemaConditionController
I1112 22:33:28.865800   26468 apiapproval_controller.go:185] Starting KubernetesAPIApprovalPolicyConformantConditionController
I1112 22:33:28.865648   26468 crd_finalizer.go:274] Starting CRDFinalizer
I1112 22:33:28.865669   26468 shared_informer.go:197] Waiting for caches to sync for crd-autoregister
I1112 22:33:28.865650   26468 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1112 22:33:28.865481   26468 controller.go:81] Starting OpenAPI AggregationController
E1112 22:33:28.873800   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:kube-scheduler" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E1112 22:33:28.873879   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E1112 22:33:28.893235   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E1112 22:33:28.893322   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list resource "services" in API group "" at the cluster scope
E1112 22:33:28.894440   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope
time="2019-11-12T22:33:28.895780324+01:00" level=info msg="Waiting for cloudcontroller rbac role to be created"
E1112 22:33:28.896429   26468 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list resource "pods" in API group "" at the cluster scope
E1112 22:33:28.896529   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
E1112 22:33:28.896594   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list resource "nodes" in API group "" at the cluster scope
E1112 22:33:28.896653   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E1112 22:33:28.896703   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:kube-scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope
E1112 22:33:28.898593   26468 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope
E1112 22:33:28.919214   26468 runtime.go:78] Observed a panic: "index out of range" (runtime error: index out of range)
goroutine 3020 [running]:
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x384c2e0, 0x70fb0b0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x384c2e0, 0x70fb0b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*storageLeases).ListLeases(0xc000d480c0, 0x3da55bd, 0x7, 0x3dad372, 0xa, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:72 +0x363
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*leaseEndpointReconciler).doReconcile(0xc0012da540, 0x3dad372, 0xa, 0xc00bafd050, 0x1, 0x1, 0x1, 0x370d5c0, 0xc003098801)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:180 +0xd8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*leaseEndpointReconciler).ReconcileEndpoints(0xc0012da540, 0x3dad372, 0xa, 0xc000d19a20, 0x10, 0x10, 0xc00bafd050, 0x1, 0x1, 0x3da9401, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:159 +0x155
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).UpdateKubernetesService(0xc00034c1c0, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:248 +0x332
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).Start(0xc00034c1c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:152 +0x56
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).PostStartHook(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:135
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.runPostStartHook.func1(0xc000dbc4b0, 0xc001132000, 0xbb2, 0xc003bb15c0, 0xc000fbc200, 0xc0126ee1e0, 0xc00a813f60)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:190 +0x6b
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.runPostStartHook(0x3dcd1a9, 0x14, 0xc000dbc4b0, 0xc001132000, 0xbb2, 0xc003bb15c0, 0xc000fbc200, 0xc0126ee1e0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:191 +0x85
created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).RunPostStartHooks
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:157 +0x13f
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 3020 [running]:
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x384c2e0, 0x70fb0b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*storageLeases).ListLeases(0xc000d480c0, 0x3da55bd, 0x7, 0x3dad372, 0xa, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:72 +0x363
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*leaseEndpointReconciler).doReconcile(0xc0012da540, 0x3dad372, 0xa, 0xc00bafd050, 0x1, 0x1, 0x1, 0x370d5c0, 0xc003098801)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:180 +0xd8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers.(*leaseEndpointReconciler).ReconcileEndpoints(0xc0012da540, 0x3dad372, 0xa, 0xc000d19a20, 0x10, 0x10, 0xc00bafd050, 0x1, 0x1, 0x3da9401, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/reconcilers/lease.go:159 +0x155
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).UpdateKubernetesService(0xc00034c1c0, 0x1, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:248 +0x332
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).Start(0xc00034c1c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:152 +0x56
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master.(*Controller).PostStartHook(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/master/controller.go:135
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.runPostStartHook.func1(0xc000dbc4b0, 0xc001132000, 0xbb2, 0xc003bb15c0, 0xc000fbc200, 0xc0126ee1e0, 0xc00a813f60)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:190 +0x6b
github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.runPostStartHook(0x3dcd1a9, 0x14, 0xc000dbc4b0, 0xc001132000, 0xbb2, 0xc003bb15c0, 0xc000fbc200, 0xc0126ee1e0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:191 +0x85
created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*GenericAPIServer).RunPostStartHooks
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/hooks.go:157 +0x13f
```

**Comment by ndarilek** [comment]
Not sure how I got past this, but a couple reboots/tweaks seems to have gotten it. Not sure if I should leave this open. I can't replicate it anymore, but it happened and scared the hell out of me. :/

I ran `systemctl stop k3s && systemctl disable k3s`, rebooted, then started `k3s server` manually.

**Comment by davidnuzik** [comment]
Hello. I'm not quite sure the nature of the issue, however you might want to edit the issue and hide your external ip address (make it x.x.x.x or something).

It would help to know what architecture. Is this on a Raspberry Pi (armhf) for example? if so what model of PI, or is this amd64 or arm64 ? etc.

Last, what command exactly are you using to install k3s? (just hide external ip address)

**Comment by ndarilek** [comment]
This is AMD64. Don't recall what command I used to run the installation since it was back in May, but I see `curl -sfL https://get.k3s.io | sh -` in my .bash_history. I received the attached log by running `k3s server >log 2>&1`.

I ran into several issues attempting the upgrade, which is part of why I put off doing it for so long. :/ Things seem to be working now, though I also had to delete and reinstall the Traefik Helm chart because the upgrade process claimed there were no Traefik releases to upgrade.

It's possible I just attempted too large of a version upgrade. In any case, things seem to be working now. If you think this is worth leaving open, I'm happy to provide additional details.

Would at least be nice if that panic got a nicer error message/exception, if possible.

**Comment by davidnuzik** [comment]
I'm glad you were able to get it to work at least. Yes a jump from v0.5.x to v0.10.2 is a pretty far jump to upgrade. For example most people based on my observation have been doing upgrades from say v0.9.1 to v0.10.2 or ver v0.8.x to v0.10.2; moving from such an older version to a much newer version was probably bound to cause some issues.

Now that we have things mostly ironed out hopefully upgrades will go smoother :)
