### ISSUE TITLE
Panic when attempt to run k3s from master on Raspberry Pi

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1193]
**Version:**
K3s master (d4959d5) (built manually)

**Describe the bug**
On my Pi4 if I attempt to run k3s-armhf (which I built myself) it will fail to start and show a panic in the debug logs. The issue is reproducible for me.

**To Reproduce**
- Start K3s:
`sudo ./k3s-armhf-12-12-19 --debug server 2>&1 | tee debuglogs2.txt`

**Expected behavior**
K3s starts properly and the node comes up.

**Actual behavior**
K3s does not start properly and there is a panic in the logs. (attached as .txt)

Here is the panic snippet from debuglog2.txt:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

goroutine 12883 [running]:
runtime: unexpected return pc for crosscall2 called from 0x0
stack: frame={sp:0xc73ea44, fp:0xc73ea8c} stack=[0xc73c000,0xc740000)
0c73e9c4:  0004fb00 <runtime.preprintpanics+4>  0007cdc8 <runtime.fatalpanic.func1+0>  0c73ea14  1091a540 
0c73e9d4:  00050050 <runtime.gopanic+704>  0c73e9e0  0c73e9c4  00066d8c <runtime.sigpanic+796> 
0c73e9e4:  0c73ea14  02fccc98  0c73f370  00000004 
0c73e9f4:  00000004  0200ba3c <github.com/google/cadvisor/container.InitializeFSContext+84>  00000000  0c73f328 
0c73ea04:  1091a540  00000028  0c73f354  1091a554 
0c73ea14:  00000000  02964500  129647a8  00000000 
0c73ea24:  00000000  00238b1c <crosscall2+68>  02a6a6e0  051a0a68 
0c73ea34:  00000000  0002c2ec <runtime.makemap_small+28>  1091a540  00238b1c <crosscall2+68> 
0c73ea44: <00000000  0c73eb4c  10df1400  00000000 
0c73ea54:  00000000  00000000  10df1424  03636cac 
0c73ea64:  00000000  00000080  1091a540  053ffa50 
0c73ea74:  00000020  02679b20  00000003  00000000 
0c73ea84:  00000000  00000000 >00000000  00000000 
0c73ea94:  00000000  00000000  00000000  00000000 
0c73eaa4:  00000000  00000000  00000000  00000000 
0c73eab4:  00000000  00000000  3b9aca00  00000000 
0c73eac4:  020802c4 <github.com/docker/docker/client.(*Client).sendRequest+200>  00000000  00000000  00000000 
0c73ead4:  00000000  00000000  00000000  00000000 
0c73eae4:  00000000  00000000  00000000  02080290 <github.com/docker/docker/client.(*Client).sendRequest+148> 
0c73eaf4:  11bb2780  10df1400  00000000  10df1400 
0c73eb04:  119a6ca0  0000000b 
panic(0x2a6a6e0, 0x51a0a68)
	/usr/local/go/src/runtime/panic.go:722 +0x2c0
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:199
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:394 +0x31c
runtime: unexpected return pc for crosscall2 called from 0x0
stack: frame={sp:0xc73ea44, fp:0xc73ea8c} stack=[0xc73c000,0xc740000)
0c73e9c4:  0004fb00 <runtime.preprintpanics+4>  0007cdc8 <runtime.fatalpanic.func1+0>  0c73ea14  1091a540 
0c73e9d4:  00050050 <runtime.gopanic+704>  0c73e9e0  0c73e9c4  00066d8c <runtime.sigpanic+796> 
0c73e9e4:  0c73ea14  02fccc98  0c73f370  00000004 
0c73e9f4:  00000004  0200ba3c <github.com/google/cadvisor/container.InitializeFSContext+84>  00000000  0c73f328 
0c73ea04:  1091a540  00000028  0c73f354  1091a554 
0c73ea14:  00000000  02964500  129647a8  00000000 
0c73ea24:  00000000  00238b1c <crosscall2+68>  02a6a6e0  051a0a68 
0c73ea34:  00000000  0002c2ec <runtime.makemap_small+28>  1091a540  00238b1c <crosscall2+68> 
0c73ea44: <00000000  0c73eb4c  10df1400  00000000 
0c73ea54:  00000000  00000000  10df1424  03636cac 
0c73ea64:  00000000  00000080  1091a540  053ffa50 
0c73ea74:  00000020  02679b20  00000003  00000000 
0c73ea84:  00000000  00000000 >00000000  00000000 
0c73ea94:  00000000  00000000  00000000  00000000 
0c73eaa4:  00000000  00000000  00000000  00000000 
0c73eab4:  00000000  00000000  3b9aca00  00000000 
0c73eac4:  020802c4 <github.com/docker/docker/client.(*Client).sendRequest+200>  00000000  00000000  00000000 
0c73ead4:  00000000  00000000  00000000  00000000 
0c73eae4:  00000000  00000000  00000000  02080290 <github.com/docker/docker/client.(*Client).sendRequest+148> 
0c73eaf4:  11bb2780  10df1400  00000000  10df1400 
0c73eb04:  119a6ca0  0000000b 
crosscall2(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/cgo/asm_arm.s:40 +0x44
created by github.com/rancher/k3s/pkg/daemons/agent.startKubelet
	/k3s/pkg/daemons/agent/agent.go:157 +0x614

```

**Additional info:**
Debug logs (full .txt)
[debuglogs2.txt](https://github.com/rancher/k3s/files/3958164/debuglogs2.txt)

Pi3b and any other armhf likely also affected (but not tested).

**Comment by davidnuzik** [comment]
Add'l info if it helps:
Build environment 32-bit ubuntu arm container running in 32-bit arm docker on arm64 host (similar to how we build K3s via the pipeline) with go 1.13.5

**Comment by davidnuzik** [comment]
This appears to be a non-issue. My build environment must not be set up quite right.
I basically tried to copy what we are doing with drone/dapper and execute the following scripts just like the dapper ci script:

./scripts/download
./scripts/build
./scripts/package

And this indeed makes a k3s-armhf binary for me but it just doesn't work right. I always get this panic.

When I build using `make` on my same build environment everything works fine and the k3s-armhf binary works normally.
