### ISSUE TITLE
k3s service can't be loaded on ubuntu 20.04

### ISSUE THREAD

**Issue by dfang** [rancher/k3s#2566]
**Environmental Info:**
K3s Version: 

```
$ k3s -v
k3s version v1.19.4+k3s1 (2532c10f)
```
Node(s) CPU architecture, OS, and Version: 

```
$ uname -a
Linux VM-0-7-ubuntu 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
Cluster Configuration:
single node cluster:

here is how i install k3s:

```
download latest release from github

wget https://get.k3s.io -O install-k3s.sh
chmod +x install-k3s.sh

sudo chmod +x k3s
sudo cp k3s /usr/local/bin/k3s

sudo mkdir -p /var/lib/rancher/k3s/agent/images
sudo cp k3s-airgap-images-amd64.tar /var/lib/rancher/k3s/agent/images

export INSTALL_K3S_SKIP_DOWNLOAD=true
export INSTALL_K3S_EXEC="--docker --write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666"

./install-k3s.sh
```

**Describe the bug:**
the service can't be loaded

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

```
$ systemctl status k3s
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2020-11-23 19:19:55 CST; 11s ago
       Docs: https://k3s.io
   Main PID: 28129 (code=exited, status=255/EXCEPTION)

Nov 23 19:19:54 VM-0-7-ubuntu systemd[1]: k3s.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 23 19:19:54 VM-0-7-ubuntu systemd[1]: k3s.service: Failed with result 'exit-code'.
Nov 23 19:19:54 VM-0-7-ubuntu systemd[1]: Failed to start Lightweight Kubernetes.
Nov 23 19:19:55 VM-0-7-ubuntu systemd[1]: k3s.service: Failed to schedule restart job: Unit k3s.service not found.
Nov 23 19:19:55 VM-0-7-ubuntu systemd[1]: k3s.service: Failed with result 'exit-code'.
```

**Additional context / logs:**

```
$ journalctl -u k3s
-- Logs begin at Tue 2020-07-28 22:32:02 CST, end at Mon 2020-11-23 19:22:01 CST. --
Nov 23 19:06:11 VM-0-7-ubuntu systemd[1]: Starting Lightweight Kubernetes...
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.158497932+08:00" level=info msg="Starting k3s v1.19.4+k3s1 (2532c10f)"
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.161154663+08:00" level=info msg="Cluster bootstrap already complete"
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.189515260+08:00" level=info msg="Configuring sqlite3 database connection pooling: maxIdle>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.189787319+08:00" level=info msg="Configuring database table schema and indexes, this may >
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.189956074+08:00" level=info msg="Database tables and indexes are up to date"
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.190807417+08:00" level=info msg="Kine listening on unix://kine.sock"
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:12.190987875+08:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-pri>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.193371   14203 server.go:652] external host was not specified, using 10.206.0.7
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.195061   14203 server.go:177] Version: v1.19.4+k3s1
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.211104   14203 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the follow>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.211394   14203 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the foll>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.213673   14203 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the follow>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.215304   14203 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the foll>
Nov 23 19:06:12 VM-0-7-ubuntu k3s[14203]: I1123 19:06:12.327862   14203 master.go:271] Using reconciler: lease
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.162821   14203 genericapiserver.go:412] Skipping API batch/v2alpha1 because it has no resources.
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.176962   14203 genericapiserver.go:412] Skipping API discovery.k8s.io/v1alpha1 because it has no res>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.195429   14203 genericapiserver.go:412] Skipping API node.k8s.io/v1alpha1 because it has no resource>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.213378   14203 genericapiserver.go:412] Skipping API rbac.authorization.k8s.io/v1alpha1 because it h>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.216946   14203 genericapiserver.go:412] Skipping API scheduling.k8s.io/v1alpha1 because it has no re>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.229541   14203 genericapiserver.go:412] Skipping API storage.k8s.io/v1alpha1 because it has no resou>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.248880   14203 genericapiserver.go:412] Skipping API apps/v1beta2 because it has no resources.
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: W1123 19:06:13.249119   14203 genericapiserver.go:412] Skipping API apps/v1beta1 because it has no resources.
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: I1123 19:06:13.264367   14203 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the follow>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: I1123 19:06:13.264636   14203 plugins.go:161] Loaded 10 validating admission controller(s) successfully in the foll>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.307223845+08:00" level=info msg="Running kube-scheduler --address=127.0.0.1 --bind-addres>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: I1123 19:06:13.307777   14203 registry.go:173] Registering SelectorSpread plugin
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: I1123 19:06:13.307886   14203 registry.go:173] Registering SelectorSpread plugin
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.308310859+08:00" level=info msg="Running kube-controller-manager --address=127.0.0.1 --al>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.310225733+08:00" level=info msg="Node token is available at /var/lib/rancher/k3s/server/t>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.310335618+08:00" level=info msg="To join node to cluster: k3s agent -s https://10.206.0.7>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311538097+08:00" level=info msg="Wrote kubeconfig /home/ubuntu/.kube/config"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311686947+08:00" level=info msg="Run: k3s kubectl"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311768378+08:00" level=info msg="Module overlay was already loaded"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311784639+08:00" level=info msg="Module nf_conntrack was already loaded"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311792283+08:00" level=info msg="Module br_netfilter was already loaded"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.311800749+08:00" level=info msg="Module iptable_nat was already loaded"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.317776180+08:00" level=info msg="Waiting for API server to become available"
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.470179960+08:00" level=info msg="Cluster-Http-Server 2020/11/23 19:06:13 http: TLS handsh>
Nov 23 19:06:13 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:13.721331321+08:00" level=info msg="Cluster-Http-Server 2020/11/23 19:06:13 http: TLS handsh>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.228199324+08:00" level=info msg="certificate CN=vm-0-7-ubuntu signed by CN=k3s-server-ca@>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.335079924+08:00" level=info msg="certificate CN=system:node:vm-0-7-ubuntu,O=system:nodes >
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.686417687+08:00" level=info msg="Connecting to proxy" url="wss://127.0.0.1:6443/v1-k3s/co>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.755274127+08:00" level=info msg="Handling backend connection request [vm-0-7-ubuntu]"
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.806127401+08:00" level=info msg="Running kubelet --address=0.0.0.0 --anonymous-auth=false>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:14.808449005+08:00" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --healthz>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from K>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: W1123 19:06:14.829463   14203 server.go:226] WARNING: all flags other than --config, --write-config-to, and --clean>
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: I1123 19:06:14.837872   14203 server.go:407] Version: v1.19.4+k3s1
Nov 23 19:06:14 VM-0-7-ubuntu k3s[14203]: I1123 19:06:14.954162   14203 dynamic_cafile_content.go:167] Starting client-ca-bundle::/var/lib/rancher/k3s/agent/>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: E1123 19:06:15.015281   14203 node.go:125] Failed to retrieve node info: nodes "vm-0-7-ubuntu" is forbidden: User ">
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: time="2020-11-23T19:06:15.056495847+08:00" level=info msg="Node CIDR assigned for: vm-0-7-ubuntu"
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.075456   14203 flannel.go:92] Determining IP address of default interface
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.078126   14203 flannel.go:105] Using interface with name eth0 and address 10.206.0.7
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.079674   14203 kube.go:117] Waiting 10m0s for node controller to sync
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.079804   14203 kube.go:300] Starting kube subnet manager
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: W1123 19:06:15.081156   14203 nvidia.go:61] NVIDIA GPU metrics will not be available: no NVIDIA devices found
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.126721   14203 server.go:640] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defau>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.128924   14203 container_manager_linux.go:289] container manager verified user specified cgroup-root>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.129039   14203 container_manager_linux.go:294] Creating Container Manager object based on Node Confi>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.130511   14203 topology_manager.go:126] [topologymanager] Creating topology manager with none policy
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.130624   14203 container_manager_linux.go:324] [topologymanager] Initializing Topology Manager with >
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.130736   14203 container_manager_linux.go:329] Creating device plugin manager: true
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.134677   14203 client.go:77] Connecting to docker on unix:///var/run/docker.sock
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.134778   14203 client.go:94] Start docker client with request timeout=2m0s
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: W1123 19:06:15.188502   14203 docker_service.go:565] Hairpin mode set to "promiscuous-bridge" but kubenet is not en>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.188723   14203 docker_service.go:241] Hairpin mode set to "hairpin-veth"
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.287718   14203 docker_service.go:256] Docker cri networking managed by cni
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: I1123 19:06:15.314602   14203 docker_service.go:261] Docker Info: &{ID:45O4:QO25:SDGN:SKUE:NG6A:PDJN:GX7S:NKH2:KZMF>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: F1123 19:06:15.314994   14203 server.go:261] failed to run Kubelet: misconfiguration: kubelet cgroup driver: "cgrou>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: goroutine 4943 [running]:
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc006f38b00, 0xaa, 0xfc)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6ea33c0, 0xc000000003, 0x0, 0x0, 0xc00a3afc70, 0x>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x6ea33c0, 0xc000000003, 0x0, 0x0, 0x1, 0xc00e4>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:718 +0x165
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).print(...)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:703
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatal(...)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1436
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0096dd8c0, 0xc00061b800,>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:261 +0x64d
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc0096dd8c0, 0xc00061b800, 0x1b, 0x20, 0xc>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0096dd8c0, 0x1, 0x0, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x375
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet.func1(0xc0096dd8c0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:31 +0x2f
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:30 +0x8d
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: goroutine 1 [select]:
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*persistConn).roundTrip(0xc00f22c360, 0xc0064f3140, 0x0, 0x0, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/transport.go:2565 +0x779
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*Transport).roundTrip(0xc00de67e00, 0xc00ada8300, 0x3d5aac0, 0x1, 0xc006d9f340)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/transport.go:582 +0xa65
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*Transport).RoundTrip(0xc00de67e00, 0xc00ada8300, 0x44afef6, 0xa, 0xc006d9f3f8)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/roundtrip.go:17 +0x35
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00f1abf00, 0xc00ada8>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/transport/round_trippers.go:159 +0x1d6
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.send(0xc00ada8200, 0x4b71360, 0xc00f1abf00, 0x0, 0x0, 0x0, 0xc00ab7cbd8, 0x203001, 0x1, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/client.go:252 +0x453
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*Client).send(0xc00c30ab40, 0xc00ada8200, 0x0, 0x0, 0x0, 0xc00ab7cbd8, 0x0, 0x1, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/client.go:176 +0xff
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*Client).do(0xc00c30ab40, 0xc00ada8200, 0x0, 0x0, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/client.go:718 +0x45f
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: net/http.(*Client).Do(...)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /usr/local/go/src/net/http/client.go:586
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/client-go/rest.(*Request).request(0xc002a74ff0, 0x4c2dfe0, 0xc0004e3e40, 0xc00>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/rest/request.go:881 +0x470
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/client-go/rest.(*Request).Do(0xc002a74ff0, 0x4c2dfe0, 0xc0004e3e40, 0x0, 0x0, >
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/rest/request.go:954 +0xf1
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/k8s.io/client-go/kubernetes/typed/core/v1.(*nodes).Update(0xc0071fe760, 0x4c2dfe0, 0x>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/kubernetes/typed/core/v1/node.go:127 +0x1d4
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/agent.configureNode(0x4c2dfe0, 0xc0004e3e40, 0xc00da695d8, 0x4c72fe0, 0xc0071fe760, 0x0,>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/agent/run.go:222 +0x303
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/agent.run(0x4c2dfe0, 0xc0004e3e40, 0xc00e3858f0, 0x6a, 0x0, 0x0, 0x0, 0x0, 0xc00a6e9440,>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/agent/run.go:109 +0x25b
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/agent.Run(0x4c2dfe0, 0xc0004e3e40, 0xc00e3858f0, 0x6a, 0x0, 0x0, 0x0, 0x0, 0xc00a6e9440,>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/agent/run.go:170 +0x438
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/cli/server.run(0xc0016f49a0, 0x6ea4840, 0xc0015deea8, 0x48)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:283 +0x1778
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/pkg/cli/server.Run(0xc0016f49a0, 0x0, 0x0)
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:38 +0x65
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/urfave/cli.HandleAction(0x3d71da0, 0x46a31d8, 0xc0016f49a0, 0xc0016f49a0, >
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:523 +0xfd
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/urfave/cli.Command.Run(0x44a5ce4, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44da2c2,>
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/command.go:174 +0x58e
Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: github.com/rancher/k3s/vendor/github.com/urfave/cli.(*App).Run(0xc0016ab880, 0xc0001c9dc0, 0x7, 0x7, 0x0, 0x0)
```

**Comment by brandond** [comment]
Can you confirm that you haven't passed any additional arguments or set any other environment variables? I personally run Ubuntu 20 for my dev hosts and test on it regularly. The message is cut off (please use `journalctl --no-pager -u k3s`) but it appears that your systemd cgroups are misconfigured?

`Nov 23 19:06:15 VM-0-7-ubuntu k3s[14203]: F1123 19:06:15.314994   14203 server.go:261] failed to run Kubelet: misconfiguration: kubelet cgroup driver: "cgrou>`

**Comment by dfang** [comment]
@brandond i didn't pass additional arguments or set any other environment variables, it's upgraded from 18.04 

i'm evaluating k3s, i've started a new instance on aws with ubuntu 20.10 AMI, but it seems `systemctl stop k3s` not works well , closing this, new issue here https://github.com/rancher/k3s/issues/2583
