### ISSUE TITLE
Race condition result in CSI fail to work with K3S sometime

### ISSUE THREAD

**Issue by yasker** [rancher/k3s#287]
`csi.(*csiPlugin).Init` was called twice if server decided to start with agent. It may cause CSI plugin to fail registration.

One time it was called by controller-manager as a part of the server, which serves the wrong parameter; the other time it was called by the kubelet.

The call of controller-manager didn't provide the hostname correct, so if it happens to be the second one calling `Init`, CSI plugin mechanism will fail with 

> I0329 21:43:23.592968       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error removing CSI driver node info from Node object error updating node: timed out waiting for the condition; caused by: [resource name may not be empty, resource name may not be empty, resource name may not be empty, resource name may not be empty],}

Here are the logs of two callings (added debug code and call stack for `nodeName` ). See the different after `NODENAME To be` in the first line:

Good call:
```
E0329 22:06:52.828785    9308 csi_plugin.go:226] kubernetes.io/csi: DEBUGGGGGGGG: CSI INIT PLUGIN NODENAME To be yasker-k3s-test
goroutine 5357 [running]:
runtime/debug.Stack(0xe3, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi.(*csiPlugin).Init(0xc0043c1bf0, 0x3a3d3a0, 0xc000c96620, 0x11, 0x5be5440)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:228 +0x2fa
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume.(*VolumePluginMgr).InitPlugins(0xc000c96628, 0xc0056ad000, 0xa, 0x10, 0x3962a60, 0xc0002c8230, 0x3a3d3a0, 0xc000c96620, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/plugins.go:536 +0x710
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.NewInitializedVolumePluginMgr(0xc0011fcd00, 0x398aee0, 0xc0047e2540, 0x398ad60, 0xc0047e2550, 0xc0059dc580, 0xc0056ad000, 0xa, 0x10, 0x3962a60, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/volume_host.go:63 +0x10b
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.NewMainKubelet(0xc001bf08a0, 0xc0056e6c60, 0xc001bf0660, 0x31f3695, 0x6, 0xc003edbfc0, 0x20, 0xc004b905c0, 0xf, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:752 +0x2c6f
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.CreateAndInitKubelet(0xc001bf08a0, 0xc0056e6c60, 0xc001bf0660, 0x31f3695, 0x6, 0xc003edbfc0, 0x20, 0xc004b905c0, 0xf, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:1000 +0x2fa
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.RunKubelet(0xc001bf0600, 0xc0056e6c60, 0x0, 0x0, 0xc003edbfc0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:895 +0x8ce
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.run(0xc001bf0600, 0xc0056e6c60, 0x0, 0xc, 0xc0024cfb38)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:707 +0x563
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.Run(0xc001bf0600, 0xc0056e6c60, 0x0, 0xc005671c00, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:397 +0x112
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0xc0055a3180, 0xc005706c00, 0x2d, 0x40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:257 +0x59e
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc0055a3180, 0xc005706c00, 0x2d, 0x40, 0xc0055a3180, 0xc005706c00)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0055a3180, 0x320ebbe, 0x12, 0xc0030abfa0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794
github.com/rancher/k3s/pkg/daemons/agent.kubelet.func1(0xc005706c00, 0x2d, 0x40, 0xc0055a3180)
	/go/src/github.com/rancher/k3s/pkg/daemons/agent/agent.go:114 +0xb2
created by github.com/rancher/k3s/pkg/daemons/agent.kubelet
	/go/src/github.com/rancher/k3s/pkg/daemons/agent/agent.go:112 +0x738
```

Bad call:
```
E0329 22:06:52.521478    9308 csi_plugin.go:226] kubernetes.io/csi: DEBUGGGGGGGG: CSI INIT PLUGIN NODENAME To be
goroutine 272 [running]:
runtime/debug.Stack(0xe3, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi.(*csiPlugin).Init(0xc0005371d0, 0x3a3d100, 0xc003a90840, 0x11, 0x5be5440)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:228 +0x2fa
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume.(*VolumePluginMgr).InitPlugins(0xc003a908d0, 0xc00295cd00, 0x2, 0x2, 0x3962a60, 0xc00106bb20, 0x3a3d100, 0xc003a90840, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/volume/plugins.go:536 +0x710
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach.NewAttachDetachController(0x3a51a40, 0xc003e6a6e0, 0x39884e0, 0xc000537120, 0x395de20, 0xc0026e2120, 0x395dd60, 0xc00295cca0, 0x395dda0, 0xc0026e2210, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/controller/volume/attachdetach/attach_detach_controller.go:138 +0x755
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.startAttachDetachController(0x39b2ee0, 0xc000afde00, 0x3a2c240, 0xc001056aa0, 0x0, 0x0, 0x0, 0x0, 0x280c, 0xc000b79f70, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:173 +0x602
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0x39b2ee0, 0xc000afde00, 0x3a2c240, 0xc001056aa0, 0x0, 0x0, 0x0, 0x0, 0x280c, 0xc000b79f70, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:461 +0x2ee
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1(0x39b0560, 0xc0000c2018)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:202 +0x4ec
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc001683ba0, 0xc00048c1e0, 0xc0011c5b70, 0xc0011f4610)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:213 +0x91b
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func1(0xc000d62280, 0xc00088b700, 0x0, 0x10)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:99 +0x27c
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc000d62280, 0xc0011b8960, 0x10, 0x1e, 0xc000d62280, 0xc0011b8960)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000d62280, 0x3247b67, 0x22, 0xc000eb27a0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794
github.com/rancher/k3s/pkg/daemons/control.controllerManager.func1(0xc0011b8960, 0x10, 0x1e, 0xc000d62280)
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:117 +0xb2
created by github.com/rancher/k3s/pkg/daemons/control.controllerManager
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:115 +0x21d
```

To reproduce:
1. Start K3S in server mode only. Use `k3s server` as the only node. `k3s server` has higher chance to reproduce this issue. `k3s --debug server` in v0.3.0 has this issue 50% of time as well.
    1.1 Run command line as `k3s server` instead of `/usr/local/bin/k3s server` or similar, to workaround https://github.com/rancher/longhorn/issues/449
2. Install Longhorn with k3s, e.g. 
```
kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yaml
```
3. Check the log of `longhorn-csi-driver`, e.g.:
```
k3s kubectl -n longhorn-system logs -l "app=longhorn-csi-plugin" -c driver-registrar
```

Error log:
You may see:
```
I0329 21:43:22.613723       1 connection.go:137] GRPC call: /csi.v0.Node/NodeGetId
I0329 21:43:22.613822       1 connection.go:138] GRPC request: {}
I0329 21:43:22.615166       1 connection.go:140] GRPC response: {"node_id":"yasker-k3s-test"}
I0329 21:43:22.616831       1 connection.go:141] GRPC error: <nil>
I0329 21:43:22.616928       1 node_register.go:63] CSI driver node ID: "yasker-k3s-test"
I0329 21:43:22.617125       1 node_register.go:86] Starting Registration Server at: /registration/io.rancher.longhorn-reg.sock
I0329 21:43:22.617484       1 node_register.go:93] Registration Server started at: /registration/io.rancher.longhorn-reg.sock
I0329 21:43:22.932570       1 main.go:111] Received GetInfo call: &InfoRequest{}
I0329 21:43:23.592968       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error removing CSI driver node info from Node object error updating node: timed out waiting for the condition; caused by: [resource name may not be empty, resource name may not be empty, resource name may not be empty, resource name may not be empty],}
E0329 21:43:23.593110       1 main.go:123] Registration process failed with error: plugin registration failed with err: error removing CSI driver node info from Node object error updating node: timed out waiting for the condition; caused by: [resource name may not be empty, resource name may not be empty, resource name may not be empty, resource name may not be empty], restarting registration container.
```

Correct log:
```
I0329 22:28:56.880850       1 node_register.go:55] Calling CSI driver to discover node ID.
I0329 22:28:56.880967       1 connection.go:137] GRPC call: /csi.v0.Node/NodeGetId
I0329 22:28:56.880995       1 connection.go:138] GRPC request: {}
I0329 22:28:56.882183       1 connection.go:140] GRPC response: {"node_id":"yasker-k3s-test"}
I0329 22:28:56.883102       1 connection.go:141] GRPC error: <nil>
I0329 22:28:56.883109       1 node_register.go:63] CSI driver node ID: "yasker-k3s-test"
I0329 22:28:56.883324       1 node_register.go:86] Starting Registration Server at: /registration/io.rancher.longhorn-reg.sock
I0329 22:28:56.883442       1 node_register.go:93] Registration Server started at: /registration/io.rancher.longhorn-reg.sock
I0329 22:28:56.893742       1 main.go:111] Received GetInfo call: &InfoRequest{}
I0329 22:28:56.904269       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
```

Patch for debug at: https://gist.github.com/yasker/24aa545cf26cb1b505e46fe23d8048f9

**Comment by yasker** [comment]
This is not an issue for Kubernetes because `kube-controller-manager` and `kubelet` are two binaries. But for k3s, they all in the same binary, so they're sharing the global variable `nim` https://github.com/rancher/k3s/blob/97243fe147202760cbc57b5e525da079a5afd2ee/vendor/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go#L91

The sharing of global variables cause the issue. The bigger problem is, there maybe other cases we don't aware yet.

**Comment by ibuildthecloud** [comment]
@yasker Thanks.  For the moment the best work around is to always run `k3s server --disable-agent` until we resolve this.

**Comment by yasker** [comment]
Verified. Now in v0.4.0-rc1, CSI nim and hostname has been properly initialized.
