### ISSUE TITLE
RPi broken on v0.4.0-rc1

### ISSUE THREAD

**Issue by ibuildthecloud** [rancher/k3s#335]
```Apr 11 23:41:18 k3s-base k3s[2084]: F0411 23:41:18.953434    2084 kubelet.go:1327] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids
Apr 11 23:41:18 k3s-base k3s[2084]: goroutine 4913 [running]:
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0x4e82e00, 0x0, 0x138, 0x1d8)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0x94
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x4e703c0, 0x3, 0x911a900, 0x4bcc54b, 0xa, 0x52f, 0x0)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2a0
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x4e703c0, 0x3, 0x2799ae0, 0x23, 0x85a9e7c, 0x1, 0x1)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x110
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(...)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1209
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0x775d900)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1327 +0x270
Apr 11 23:41:18 k3s-base k3s[2084]: sync.(*Once).Do(0x775dd20, 0x92c4f10)
Apr 11 23:41:18 k3s-base k3s[2084]:         /usr/local/go/src/sync/once.go:44 +0xb8
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0x775d900)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2153 +0x334
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x92a2610)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x4c
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x92a2610, 0x2a05f200, 0x1, 0x0, 0x0, 0x1, 0x67158c0)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xfc
Apr 11 23:41:18 k3s-base k3s[2084]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x92a2610, 0x2a05f200, 0x1, 0x67158c0)
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x48
Apr 11 23:41:18 k3s-base k3s[2084]: created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
Apr 11 23:41:18 k3s-base k3s[2084]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1376 +0xfc
Apr 11 23:41:21 k3s-base systemd[1]: k3s.service: Main process exited, code=exited, status=255/n/a
Apr 11 23:41:21 k3s-base systemd[1]: k3s.service: Unit entered failed state.
Apr 11 23:41:21 k3s-base systemd[1]: k3s.service: Failed with result 'exit-code'.
```

**Comment by mak3r** [comment]
I have found that installing and running v0.4.0-rc3 resolves the issues. This is true for both installation methods - downloading the release version and also using the scripted install.

```
./k3s-armhf -v
k3s-armhf version v0.4.0-rc3 (be24f83)
```

```
sudo ./k3s-armhf kubectl get node
NAME       STATUS   ROLES    AGE   VERSION
k3s-mgmt   Ready    <none>   10m   v1.14.1-k3s.4
```

**CONTENT BELOW IS A VALIDATION/RECREATION OF THE ISSUE AS SEEN ON RPi**

I get the following error when I install v0.4.0-rc1 on the RPi3B+ using the install script
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.4.0-rc1 sh -
[INFO]  Using v0.4.0-rc1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.4.0-rc1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.4.0-rc1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  systemd: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
pi@k3s-mgmt:~ $ k3s kubectl get node
The connection to the server localhost:6443 was refused - did you specify the right host or port?
```

I get the following output on an RPi3B+ when I dl the v0.4.0-rc1 candidate
```
sudo ./k3s-armhf server &
[1] 3477
INFO[0000] Preparing data dir /var/lib/rancher/k3s/data/9bcbaf759eaf361bbc74607d42ded491b37004d97f50b5d312a6c4305fb80025
INFO[2019-04-16T01:53:43.863170714+01:00] Starting k3s v0.4.0-rc1 (b5217e2)
INFO[2019-04-16T01:54:25.649948569+01:00] Running kube-apiserver --advertise-port=6445 --tls-cert-file=/var/lib/rancher/k3s/server/tls/localhost.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/token-node.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/token-node.key --watch-cache=false --allow-privileged=true --insecure-port=0 --secure-port=6444 --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --api-audiences=unknown --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --bind-address=127.0.0.1 --service-account-issuer=k3s --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --advertise-address=127.0.0.1 --authorization-mode=Node,RBAC --tls-private-key-file=/var/lib/rancher/k3s/server/tls/localhost.key
INFO[2019-04-16T01:54:39.905038364+01:00] Running kube-scheduler --secure-port=0 --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --leader-elect=false --port=10251 --bind-address=127.0.0.1
INFO[2019-04-16T01:54:39.907050137+01:00] Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --port=10252 --secure-port=0 --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --root-ca-file=/var/lib/rancher/k3s/server/tls/token-ca.crt --leader-elect=false
INFO[2019-04-16T01:54:40.645962390+01:00] Creating CRD listenerconfigs.k3s.cattle.io
INFO[2019-04-16T01:54:40.795345273+01:00] Creating CRD addons.k3s.cattle.io
INFO[2019-04-16T01:54:40.802317783+01:00] Creating CRD helmcharts.k3s.cattle.io
INFO[2019-04-16T01:54:40.817452309+01:00] Waiting for CRD listenerconfigs.k3s.cattle.io to become available
INFO[2019-04-16T01:54:41.322320007+01:00] Done waiting for CRD listenerconfigs.k3s.cattle.io to become available
INFO[2019-04-16T01:54:41.322410210+01:00] Waiting for CRD addons.k3s.cattle.io to become available
INFO[2019-04-16T01:54:41.826674276+01:00] Done waiting for CRD addons.k3s.cattle.io to become available
INFO[2019-04-16T01:54:41.826749332+01:00] Waiting for CRD helmcharts.k3s.cattle.io to become available
INFO[2019-04-16T01:54:42.338017497+01:00] Done waiting for CRD helmcharts.k3s.cattle.io to become available
INFO[2019-04-16T01:54:42.363588296+01:00] Listening on :6443
INFO[2019-04-16T01:54:56.054835732+01:00] Node token is available at /var/lib/rancher/k3s/server/node-token
INFO[2019-04-16T01:54:56.054937218+01:00] To join node to cluster: k3s agent -s https://192.168.43.32:6443 -t ${NODE_TOKEN}
INFO[2019-04-16T01:54:56.060474905+01:00] Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik-1.64.0.tgz
INFO[2019-04-16T01:54:56.061613008+01:00] Writing manifest: /var/lib/rancher/k3s/server/manifests/coredns.yaml
INFO[2019-04-16T01:54:56.061980079+01:00] Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml
INFO[2019-04-16T01:54:56.802460049+01:00] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml
INFO[2019-04-16T01:54:56.802549534+01:00] Run: k3s-armhf kubectl
INFO[2019-04-16T01:54:56.802582041+01:00] k3s is up and running
INFO[2019-04-16T01:54:57.539203089+01:00] Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log
INFO[2019-04-16T01:54:57.539495687+01:00] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
INFO[2019-04-16T01:54:57.545269073+01:00] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused"
INFO[2019-04-16T01:54:58.578049246+01:00] Connecting to wss://localhost:6443/v1-k3s/connect
INFO[2019-04-16T01:54:58.578653925+01:00] Connecting to proxy                           url="wss://localhost:6443/v1-k3s/connect"
INFO[2019-04-16T01:54:58.722430637+01:00] Handling backend connection request [k3s-mgmt]
WARN[2019-04-16T01:54:58.727075710+01:00] Disabling CPU quotas due to missing cpu.cfs_period_us
INFO[2019-04-16T01:54:58.727863410+01:00] Running kubelet --container-runtime=remote --healthz-bind-address=127.0.0.1 --allow-privileged=true --eviction-hard=imagefs.available<5%,nodefs.available<5% --fail-swap-on=false --cgroup-driver=cgroupfs --cert-dir=/var/lib/rancher/k3s/agent/kubelet/pki --seccomp-profile-root=/var/lib/rancher/k3s/agent/kubelet/seccomp --anonymous-auth=false --cluster-domain=cluster.local --kubeconfig=/var/lib/rancher/k3s/agent/kubeconfig.yaml --cni-bin-dir=/var/lib/rancher/k3s/data/9bcbaf759eaf361bbc74607d42ded491b37004d97f50b5d312a6c4305fb80025/bin --resolv-conf=/etc/resolv.conf --address=127.0.0.1 --cpu-cfs-quota=false --read-only-port=0 --root-dir=/var/lib/rancher/k3s/agent/kubelet --cluster-dns=10.43.0.10 --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --hostname-override=k3s-mgmt --runtime-cgroups=/systemd/user.slice/user-1000.slice --kubelet-cgroups=/systemd/user.slice/user-1000.slice --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --serialize-image-pulls=false --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.pem
Flag --allow-privileged has been deprecated, will be removed in a future version
INFO[2019-04-16T01:54:58.923994215+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
INFO[2019-04-16T01:55:01.003434783+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
INFO[2019-04-16T01:55:03.007326329+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
INFO[2019-04-16T01:55:05.011432671+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
INFO[2019-04-16T01:55:07.015170912+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
INFO[2019-04-16T01:55:09.019341380+01:00] waiting for node k3s-mgmt: nodes "k3s-mgmt" not found
F0416 01:55:09.907989    3481 kubelet.go:1327] Failed to start ContainerManager failed to initialize top level QOS containers: failed to update top level Burstable QOS cgroup : failed to set supported cgroup subsystems for cgroup [kubepods burstable]: Failed to find subsystem mount for required subsystem: pids
goroutine 9052 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0x4e82e00, 0x0, 0x138, 0x1d8)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0x94
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x4e703c0, 0x3, 0x92b45a0, 0x4bcc54b, 0xa, 0x52f, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2a0
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x4e703c0, 0x3, 0x2799ae0, 0x23, 0x94abe7c, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x110
github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1209
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0x9306000)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1327 +0x270
sync.(*Once).Do(0x9306420, 0x9428f10)
	/usr/local/go/src/sync/once.go:44 +0xb8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0x9306000)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2153 +0x334
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x941c178)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x4c
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x941c178, 0x2a05f200, 0x1, 0x0, 0x0, 0x1, 0x5b178c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xfc
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x941c178, 0x2a05f200, 0x1, 0x5b178c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x48
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1376 +0xfc
INFO[2019-04-16T01:55:11.072897478+01:00] waiting for node k3s-mgmt CIDR not assigned yet

[1]+  Exit 255                sudo ./k3s-armhf server
```
