### ISSUE TITLE
k3s: Failing to run on arch linux (via k3d)

### ISSUE THREAD

**Issue by jaredallard** [rancher/k3s#471]
**Describe the bug**
Attempted to run via k3d, ran into this issue:

```
time="2019-05-11T11:28:13.544568011Z" level=info msg="Starting k3s v0.5.0 (8c0116dd)"
time="2019-05-11T11:28:14.499035295Z" level=info msg="Running kube-apiserver --advertise-port=6445 --tls-cert-file=/var/lib/rancher/k3s/server/tls/localhost.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/localhost.key --api-audiences=unknown --requestheader-extra-headers-prefix=X-Remote-Extra- --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --service-account-issuer=k3s --kubelet-client-key=/var/lib/rancher/k3s/server/tls/token-node.key --authorization-mode=Node,RBAC --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --advertise-address=127.0.0.1 --insecure-port=0 --secure-port=6444 --basic-auth-file=/var/lib/rancher/k3s/server/cred/passwd --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/token-node-1.crt --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --watch-cache=false --allow-privileged=true --bind-address=127.0.0.1 --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --requestheader-allowed-names=kubernetes-proxy --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User"
E0511 11:28:14.906373       1 prometheus.go:138] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.907136       1 prometheus.go:150] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.907205       1 prometheus.go:162] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.907282       1 prometheus.go:174] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.907333       1 prometheus.go:189] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.907523       1 prometheus.go:202] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
W0511 11:28:14.938148       1 genericapiserver.go:315] Skipping API batch/v2alpha1 because it has no resources.
W0511 11:28:14.945112       1 genericapiserver.go:315] Skipping API node.k8s.io/v1alpha1 because it has no resources.
E0511 11:28:14.955357       1 prometheus.go:138] failed to register depth metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.955381       1 prometheus.go:150] failed to register adds metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.955455       1 prometheus.go:162] failed to register latency metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.955523       1 prometheus.go:174] failed to register work_duration metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.955543       1 prometheus.go:189] failed to register unfinished_work_seconds metric admission_quota_controller: duplicate metrics collector registration attempted
E0511 11:28:14.955559       1 prometheus.go:202] failed to register longest_running_processor_microseconds metric admission_quota_controller: duplicate metrics collector registration attempted
time="2019-05-11T11:28:14.958696399Z" level=info msg="Running kube-scheduler --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --leader-elect=false --port=10251 --bind-address=127.0.0.1 --secure-port=0"
time="2019-05-11T11:28:14.959016903Z" level=info msg="Running kube-controller-manager --cluster-cidr=10.42.0.0/16 --root-ca-file=/var/lib/rancher/k3s/server/tls/token-ca.crt --allocate-node-cidrs=true --port=10252 --bind-address=127.0.0.1 --secure-port=0 --kubeconfig=/var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --leader-elect=false"
E0511 11:28:14.960444       1 controller.go:148] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/127.0.0.1, ResourceVersion: 0, AdditionalErrorMsg: 
W0511 11:28:14.967834       1 authorization.go:47] Authorization is disabled
W0511 11:28:14.967845       1 authentication.go:55] Authentication is disabled
time="2019-05-11T11:28:14.999437908Z" level=info msg="Creating CRD listenerconfigs.k3s.cattle.io"
time="2019-05-11T11:28:15.003951930Z" level=info msg="Creating CRD addons.k3s.cattle.io"
time="2019-05-11T11:28:15.004930268Z" level=info msg="Creating CRD helmcharts.k3s.cattle.io"
time="2019-05-11T11:28:15.006438186Z" level=info msg="Waiting for CRD listenerconfigs.k3s.cattle.io to become available"
time="2019-05-11T11:28:15.509946465Z" level=info msg="Done waiting for CRD listenerconfigs.k3s.cattle.io to become available"
time="2019-05-11T11:28:15.509998783Z" level=info msg="Waiting for CRD addons.k3s.cattle.io to become available"
time="2019-05-11T11:28:16.012844194Z" level=info msg="Done waiting for CRD addons.k3s.cattle.io to become available"
time="2019-05-11T11:28:16.012918894Z" level=info msg="Waiting for CRD helmcharts.k3s.cattle.io to become available"
time="2019-05-11T11:28:16.515801837Z" level=info msg="Done waiting for CRD helmcharts.k3s.cattle.io to become available"
time="2019-05-11T11:28:16.521060421Z" level=info msg="Listening on :6443"
time="2019-05-11T11:28:17.013020971Z" level=info msg="Node token is available at /var/lib/rancher/k3s/server/node-token"
time="2019-05-11T11:28:17.013092691Z" level=info msg="To join node to cluster: k3s agent -s https://172.20.0.2:6443 -t ${NODE_TOKEN}"
time="2019-05-11T11:28:17.018291748Z" level=info msg="Writing static file: /var/lib/rancher/k3s/server/static/charts/traefik-1.64.0.tgz"
time="2019-05-11T11:28:17.018946698Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml"
time="2019-05-11T11:28:17.019373500Z" level=info msg="Writing manifest: /var/lib/rancher/k3s/server/manifests/coredns.yaml"
time="2019-05-11T11:28:17.171229328Z" level=info msg="Wrote kubeconfig /output/kubeconfig.yaml"
time="2019-05-11T11:28:17.171282294Z" level=info msg="Run: k3s kubectl"
time="2019-05-11T11:28:17.171299931Z" level=info msg="k3s is up and running"
time="2019-05-11T11:28:17.542423144Z" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
time="2019-05-11T11:28:17.542698086Z" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd"
time="2019-05-11T11:28:17.543293151Z" level=info msg="Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory\""
W0511 11:28:18.411099       1 lease.go:222] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
time="2019-05-11T11:28:18.546674657Z" level=warning msg="failed to start br_netfilter module"
time="2019-05-11T11:28:18.548620147Z" level=info msg="Connecting to wss://localhost:6443/v1-k3s/connect"
time="2019-05-11T11:28:18.548686609Z" level=info msg="Connecting to proxy" url="wss://localhost:6443/v1-k3s/connect"
time="2019-05-11T11:28:18.589298750Z" level=info msg="Handling backend connection request [k3d-k3s-default-server]"
time="2019-05-11T11:28:18.591937155Z" level=warning msg="Disabling CPU quotas due to missing cpu.cfs_period_us"
time="2019-05-11T11:28:18.592319072Z" level=info msg="Running kubelet --healthz-bind-address=127.0.0.1 --seccomp-profile-root=/var/lib/rancher/k3s/agent/kubelet/seccomp --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --cluster-dns=10.43.0.10 --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.pem --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --container-runtime=remote --serialize-image-pulls=false --address=0.0.0.0 --hostname-override=k3d-k3s-default-server --cpu-cfs-quota=false --allow-privileged=true --cluster-domain=cluster.local --kubeconfig=/var/lib/rancher/k3s/agent/kubeconfig.yaml --authorization-mode=Webhook --cert-dir=/var/lib/rancher/k3s/agent/kubelet/pki --tls-cert-file=/var/lib/rancher/k3s/agent/token-node.crt --cgroup-driver=cgroupfs --resolv-conf=/tmp/k3s-resolv.conf --anonymous-auth=false --tls-private-key-file=/var/lib/rancher/k3s/agent/token-node.key --read-only-port=0 --fail-swap-on=false --root-dir=/var/lib/rancher/k3s/agent/kubelet --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --authentication-token-webhook=true --cni-bin-dir=/bin"
Flag --allow-privileged has been deprecated, will be removed in a future version
W0511 11:28:18.592626       1 server.go:214] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
W0511 11:28:18.597757       1 proxier.go:480] Failed to read file /lib/modules/5.0.13-arch1-1-ARCH/modules.builtin with error open /lib/modules/5.0.13-arch1-1-ARCH/modules.builtin: no such file or directory. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.598977       1 fs.go:218] stat failed on /dev/mapper/vg1-root with error: no such file or directory
W0511 11:28:18.599031       1 proxier.go:493] Failed to load kernel module ip_vs with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.600211       1 proxier.go:493] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.601220       1 proxier.go:493] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.603924       1 proxier.go:493] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.604701       1 info.go:52] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
W0511 11:28:18.604823       1 proxier.go:493] Failed to load kernel module nf_conntrack with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0511 11:28:18.617235       1 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
W0511 11:28:18.624321       1 fs.go:556] stat failed on /dev/mapper/vg1-root with error: no such file or directory
E0511 11:28:18.624463       1 cri_stats_provider.go:373] Failed to get the info of the filesystem with mountpoint "/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs": failed to get device for dir "/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs": could not find device with major: 0, minor: 27 in cached partitions map.
E0511 11:28:18.624521       1 kubelet.go:1250] Image garbage collection failed once. Stats initialization may not have completed yet: invalid capacity 0 on image filesystem
W0511 11:28:18.632923       1 fs.go:556] stat failed on /dev/mapper/vg1-root with error: no such file or directory
F0511 11:28:18.632948       1 kubelet.go:1327] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/lib/rancher/k3s/agent/kubelet": could not find device with major: 0, minor: 27 in cached partitions map
goroutine 6951 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0xc000833300, 0xc000d13b00, 0xf6, 0xfd)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xb1
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x5f95ca0, 0xc000000003, 0xc001430c40, 0x5cb919c, 0xa, 0x52f, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2d9
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x5f95ca0, 0xc000000003, 0x3407386, 0x23, 0xc002699d38, 0x1, 0x1)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x14e
github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1209
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0xc0026fdb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1327 +0x330
sync.(*Once).Do(0xc0026fe228, 0xc003381e70)
	/usr/local/go/src/sync/once.go:44 +0xb3
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0xc0026fdb00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2153 +0x3eb
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00240bce0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00240bce0, 0x12a05f200, 0x0, 0x1, 0xc0000bc360)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00240bce0, 0x12a05f200, 0xc0000bc360)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1376 +0x14b
time="2019-05-11T11:28:18.683459623Z" level=info msg="waiting for node k3d-k3s-default-server: nodes \"k3d-k3s-default-server\" not found"
W0511 11:28:18.682583       1 node.go:113] Failed to retrieve node info: nodes "k3d-k3s-default-server" not found
```

**To Reproduce**

```bash
# use latests k3d
$ k3d create --workers=1
$ docker ps -a
$ docker logs <service_container_id>
```

**Expected behavior**
expected k3s to run

**Additional context**

I suspect this may be due to me running luks in lvm, so I will include disk information below plus other details:

```
$ lsblk
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
nvme0n1        259:0    0   477G  0 disk  
├─nvme0n1p1    259:1    0   488M  0 part  /boot
└─nvme0n1p2    259:2    0 476.5G  0 part  
  └─crypt      254:0    0 476.5G  0 crypt 
    ├─vg1-swap 254:1    0     8G  0 lvm   [SWAP]
    ├─vg1-root 254:2    0    80G  0 lvm   /
    └─vg1-home 254:3    0 388.5G  0 lvm   /home
$ uname -a
Linux sterben 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux
```

Please let me know if I can provide anything else, I don't have much to go off of right now! Also, unsure if this belongs on k3d or k3s or not, assuming that it belongs here since it's not CLI related (i assume)

**Comment by jaredallard** [comment]
For what it's worth, it worked for a little bit, but then crashed with the same issue after about ~10m

**Comment by jaredallard** [comment]
Confirmed related to disk by removing the `/var/rancher/.../k3s` mount created by `-v`

**Comment by jaredallard** [comment]
Resolved by adding `-v /dev/mapper:/dev/mapper` to the docker container running k3s, which allows it to stat the filesystem, which then adds it to the partition cache.
