### ISSUE TITLE
k3s v0.6.0 - A goroutine exception was thrown trying to connect to a postgres-like database (cockroachDB)

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#549]
**Describe the bug**
A goroutine exception was thrown trying to connect to a postgres-like database (cockroachDB)

**To Reproduce**

```bash
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable-agent --cluster-cidr <clus-net>/<clus-cidr> --service-cidr <svc-net>/<svc-cidr> --storage-endpoint postgres://<pg-user>:<pg-pass>@<pg-host>:<pg-port>/<pg-db>?sslmode=require --data-dir /media/data/rancher/k3s" sh -
```

**Expected behavior**
1) Build \<pg-db\> on \<pg-host\> after a secure connection to the specified endpoint
2) Launch k3s as dedicated master node with cockroachDB as storage backend

**Screenshots**
N/A

**Additional context**
Here the output of **journalctl -u k3s**

```
<...omitted...> k3s[1987]: <...omitted...>   1987 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry {[postgres://<pg-user>:<pg-pass>@<pg-host>:<pg-port>/<pg-db>?sslmode=require]   } false true 0x40005efe60 apiextensions.k8
<...omitted...> k3s[1987]: goroutine 99 [running]:
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0x4000970500, 0x4000b1a000, 0x161, 0x39d)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xac
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x5b40a60, 0x4000000003, 0x40004beaf0, 0x585172c, 0x14, 0x39, 0x0)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2d8
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x5b40a60, 0x3, 0x2fb670e, 0x37, 0x4000776d98, 0x2, 0x2)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x114
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(...)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1209
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic.NewRawStorage(0x4000293e60, 0x1db60c0, 0x2c8c1e0, 0x4000543b80)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/storage_decorator.go:57 +0xf4
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic.UndecoratedStorage(0x4000293e60, 0x36fe540, 0x4000543b80, 0x4000055320, 0x2f, 0x4000aa7200, 0x303aa38, 0x303aa20, 0x303b168, 0x40000552f0, ...)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/storage_decorator.go:48 +0x28
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).CompleteWithOptions(0x400029cd80, 0x4000777138, 0x3708740, 0x4000aa71a0)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1289 +0x618
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition.NewREST(0x40000fbce0, 0x36bc040, 0x4000293e60, 0x4000294348)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/registry/customresourcedefinition/etcd.go:55 +0x28c
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.completedConfig.New(0x400057dd20, 0x4000051588, 0x377e020, 0x5b62c00, 0x4000490aa0, 0x4000461040, 0x10)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:142 +0xc14
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.createAPIExtensionsServer(0x4000051580, 0x377e020, 0x5b62c00, 0x1, 0x36bbca0, 0x4000547430)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/apiextensions.go:94 +0x50
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.CreateServerChain(0x40003dc240, 0x4000484540, 0x2f08c3d, 0xc, 0x40009b3c78, 0x1)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:186 +0x25c
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0x40003dc240, 0x4000484540, 0x0, 0x0)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:150 +0xc4
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.NewAPIServerCommand.func1(0x40004e0000, 0x40002ad180, 0x0, 0x1b, 0x0, 0x0)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:110 +0xe0
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0x40004e0000, 0x4000026c00, 0x1b, 0x20, 0x40004e0000, 0x4000026c00)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:756 +0x328
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x40004e0000, 0x2f2ffbd, 0x19, 0x4000071f98)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x228
<...omitted...> k3s[1987]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794
<...omitted...> k3s[1987]: github.com/rancher/k3s/pkg/daemons/control.apiServer.func1(0x4000026c00, 0x1b, 0x20, 0x40004e0000)
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:193 +0xa0
<...omitted...> k3s[1987]: created by github.com/rancher/k3s/pkg/daemons/control.apiServer
<...omitted...> k3s[1987]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:191 +0xc60
<...omitted...> systemd[1]: k3s.service: Main process exited, code=exited, status=255/n/a
```

**Comment by erikwilson** [comment]
@giminni It looks like you have omitted the actual error message. It should be something like this:
`
F0619 03:31:07.453896    8152 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry {[postgres://root:secret@10.0.2.2?sslmode=verify-full]   } false true 0xc000507cb0 apiextensions.k8s.io/v1beta1 <nil> 5m0s 1m0s}), err (x509: certificate signed by unknown authority)
`

**Comment by giminni** [comment]
@erikwilson I forgot to add storage-cafile, storage-certfile and storage-keyfile.
The storage backend is now registered to k3s. Thanks for point me into the right direction.
