### ISSUE TITLE
unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system

### ISSUE THREAD

**Issue by geogeim** [rancher/k3s#89]
**Describe the bug**
I tried to run the k3s docker image v0.1.0 from https://hub.docker.com/r/rancher/k3s on windows hyperv docker latest version. 

**To Reproduce**
```
C:\Users\Marian>docker --version
Docker version 18.09.2, build 6247962
C:\Users\Marian>docker run -it e936fa0dc085 server
INFO[2019-02-28T12:45:55.746780800Z] Starting k3s v0.1.0 (91251aa)
INFO[2019-02-28T12:45:56.748095900Z] Running kube-apiserver --watch-cache=false --cert-dir /var/lib/rancher/k3s/server/tls/temporary-certs --allow-privileged=true --authorization-mode Node,RBAC --service-account-signing-key-file /var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range 10.43.0.0/16 --advertise-port 6445 --advertise-address 127.0.0.1 --insecure-port 0 --secure-port 6444 --bind-address 127.0.0.1 --tls-cert-file /var/lib/rancher/k3s/server/tls/localhost.crt --tls-private-key-file /var/lib/rancher/k3s/server/tls/localhost.key --service-account-key-file /var/lib/rancher/k3s/server/tls/service.key --service-account-issuer k3s --api-audiences unknown --basic-auth-file /var/lib/rancher/k3s/server/cred/passwd --kubelet-client-certificate /var/lib/rancher/k3s/server/tls/token-node.crt --kubelet-client-key /var/lib/rancher/k3s/server/tls/token-node.key
INFO[2019-02-28T12:45:57.278037100Z] Running kube-scheduler --kubeconfig /var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --port 0 --secure-port 0 --leader-elect=false
INFO[2019-02-28T12:45:57.286242000Z] Running kube-controller-manager --kubeconfig /var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --service-account-private-key-file /var/lib/rancher/k3s/server/tls/service.key --allocate-node-cidrs --cluster-cidr 10.42.0.0/16 --root-ca-file /var/lib/rancher/k3s/server/tls/token-ca.crt --port 0 --secure-port 0 --leader-elect=false
INFO[2019-02-28T12:45:57.449096000Z] Creating CRD listenerconfigs.k3s.cattle.io
INFO[2019-02-28T12:45:57.461354300Z] Creating CRD addons.k3s.cattle.io
INFO[2019-02-28T12:45:57.467035400Z] Creating CRD helmcharts.k3s.cattle.io
INFO[2019-02-28T12:45:57.471322100Z] Waiting for CRD listenerconfigs.k3s.cattle.io to become available
INFO[2019-02-28T12:45:57.975090300Z] Done waiting for CRD listenerconfigs.k3s.cattle.io to become available
INFO[2019-02-28T12:45:57.975128000Z] Waiting for CRD addons.k3s.cattle.io to become available
INFO[2019-02-28T12:45:58.476987000Z] Done waiting for CRD addons.k3s.cattle.io to become available
INFO[2019-02-28T12:45:58.477034800Z] Waiting for CRD helmcharts.k3s.cattle.io to become available
INFO[2019-02-28T12:45:58.978962800Z] Done waiting for CRD helmcharts.k3s.cattle.io to become available
INFO[2019-02-28T12:45:58.982298500Z] Listening on :6443
INFO[2019-02-28T12:45:59.370349300Z] Writing manifest: /var/lib/rancher/k3s/server/manifests/coredns.yaml
INFO[2019-02-28T12:45:59.370934300Z] Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml
INFO[2019-02-28T12:46:00.071571300Z] Node token is available at /var/lib/rancher/k3s/server/node-token
INFO[2019-02-28T12:46:00.071601500Z] To join node to cluster: k3s agent -s https://172.17.0.2:6443 -t ${NODE_TOKEN}
INFO[2019-02-28T12:46:00.152979300Z] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml
INFO[2019-02-28T12:46:00.153038200Z] Run: k3s kubectl
INFO[2019-02-28T12:46:00.153044800Z] k3s is up and running
INFO[2019-02-28T12:46:00.254137200Z] Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log
INFO[2019-02-28T12:46:00.254548200Z] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
INFO[2019-02-28T12:46:00.255744400Z] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory"
WARN[2019-02-28T12:46:01.257991500Z] failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
WARN[2019-02-28T12:46:01.258050500Z] failed to write value 1 at /proc/sys/net/ipv4/ip_forward: open /proc/sys/net/ipv4/ip_forward: read-only file system
INFO[2019-02-28T12:46:01.259155300Z] Connecting to wss://localhost:6443/v1-k3s/connect
INFO[2019-02-28T12:46:01.259230400Z] Connecting to proxy                           url="wss://localhost:6443/v1-k3s/connect"
INFO[2019-02-28T12:46:01.271341200Z] Handling backend connection request [18b58495960a]
WARN[2019-02-28T12:46:01.273416800Z] Disabling CPU quotas due to missing cpu.cfs_period_us
INFO[2019-02-28T12:46:01.273514300Z] Running kubelet --healthz-bind-address 127.0.0.1 --read-only-port 0 --allow-privileged=true --cluster-domain cluster.local --kubeconfig /var/lib/rancher/k3s/agent/kubeconfig.yaml --eviction-hard imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --cgroup-driver cgroupfs --root-dir /var/lib/rancher/k3s/agent/kubelet --cert-dir /var/lib/rancher/k3s/agent/kubelet/pki --seccomp-profile-root /var/lib/rancher/k3s/agent/kubelet/seccomp --cni-conf-dir /var/lib/rancher/k3s/agent/etc/cni/net.d --cni-bin-dir /bin --cluster-dns 10.43.0.10 --container-runtime remote --container-runtime-endpoint unix:///run/k3s/containerd/containerd.sock --address 127.0.0.1 --anonymous-auth=false --client-ca-file /var/lib/rancher/k3s/agent/client-ca.pem --hostname-override 18b58495960a --cpu-cfs-quota=false
Flag --allow-privileged has been deprecated, will be removed in a future version
INFO[2019-02-28T12:46:01.339032300Z] waiting for node 18b58495960a: nodes "18b58495960a" not found
F0228 12:46:01.339206       1 server.go:377] unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system
goroutine 5872 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0xc00059d400, 0xc000c3a500, 0xc1, 0x13a)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xd4
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x57d9d80, 0xc000000003, 0xc00067a160, 0x5363667, 0x9, 0x179, 0x0)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x306
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printDepth(0x57d9d80, 0xc000000003, 0x1, 0xc0025c5cf0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:669 +0x129
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).print(0x57d9d80, 0xc000000003, 0xc0025c5cf0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:660 +0x5a
github.com/rancher/k3s/vendor/k8s.io/klog.Fatal(0xc0025c5cf0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1187 +0x53
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc0013b9900, 0xc002d53b00, 0x0, 0x8)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:377 +0x19b
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc0013b9900, 0xc002d8fb80, 0x8, 0x8, 0xc0013b9900, 0xc002d8fb80)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:760 +0x2cc
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0013b9900, 0xc003abdfb8, 0x1129e0f, 0x35a9720)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0013b9900, 0xc003abdfaf, 0xc00258a380)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794 +0x2b
github.com/rancher/k3s/pkg/daemons/agent.kubeProxy.func1(0xc0013b9900)
        /go/src/github.com/rancher/k3s/pkg/daemons/agent/agent.go:43 +0x2f
created by github.com/rancher/k3s/pkg/daemons/agent.kubeProxy
        /go/src/github.com/rancher/k3s/pkg/daemons/agent/agent.go:42 +0x1c5
```

**Comment by ibuildthecloud** [comment]
The server runs the agent by default and the agent must be ran in a privileged container.  Add `--privileged --tmpfs /run --tmpfs /var/run`.  If you want the state persisted also add `-v k3s-state:/var/lib/rancher/k3s`

**Comment by geogeim** [comment]
Thank you ❤️, that solved the problem. 
I now get another issue: 
```
INFO[2019-02-28T15:44:00.616524900Z] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: no such file or directory"
WARN[2019-02-28T15:44:01.618694100Z] failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
...
INFO[2019-02-28T15:44:01.734540300Z] waiting for node 7f4c530f8528: nodes "7f4c530f8528" not found
INFO[2019-02-28T15:44:03.739751300Z] waiting for node 7f4c530f8528 CIDR not assigned yet
INFO[2019-02-28T15:44:05.743248400Z] waiting for node 7f4c530f8528 CIDR not assigned yet
```
If you could point me in the right direction I would be grateful.
